### ISSUE TITLE
Benign? error in install on debian 9

### ISSUE THREAD

**Issue by leandro-navarro** [Clommunity/cloudynitzar#10]
[Cloudynitzar] - Performing specific changes for Debian stretch...
[Cloudynitzar] - Detecting the primary network interface...
[Cloudynitzar] - The primary network interface is enp1s0. Saving it...

[Cloudynitzar] - Starting Cloudy web interface...
cat: /var/run/cdistro.pid: No such file or directory
/etc/init.d/cdistro: 35: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
rm: cannot remove '/var/run/cdistro.pid': No such file or directory
cat: /var/run/cdistrod.pid: No such file or directory
/etc/init.d/cdistro: 37: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
rm: cannot remove '/var/run/cdistrod.pid': No such file or directory

Anyway, Cloudy seems to work.

**Comment by rogerpueyo** [comment]
The error seems to be caused by cDistro being restarted (by stopping and starting the daemon) when it is still stopped, so there is nothing to actually stop.

Similar to https://github.com/Clommunity/package-serf/issues/6

**Comment by rogerpueyo** [comment]
For example:

```
root@cloudev:~# /etc/init.d/cdistro stop
root@cloudev:~# /etc/init.d/cdistro restart
cat: /var/run/cdistro.pid: El fitxer o directori no existeix
/etc/init.d/cdistro: 35: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
rm: no s’ha pogut eliminar «/var/run/cdistro.pid»: El fitxer o directori no existeix
cat: /var/run/cdistrod.pid: El fitxer o directori no existeix
/etc/init.d/cdistro: 37: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
rm: no s’ha pogut eliminar «/var/run/cdistrod.pid»: El fitxer o directori no existeix
```
